### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by tuhinsbuddy** [hyperverge/capture-ios-sdk#5]
<img width="484" alt="Screenshot 2020-03-26 at 9 47 01 PM" src="https://user-images.githubusercontent.com/20298863/77669940-87673480-6fab-11ea-8bdd-3478c2bc862c.png">

Please build with latest Xcode/SDK and update.

**Comment by minhchienwikipedia** [comment]
Same here! Any update?

**Comment by tuhinsbuddy** [comment]
Any update?

**Comment by minhphung210** [comment]
same issue

**Comment by tuhinsbuddy** [comment]
After forcefully mentioning the `.git` path inside `Podfile` it is working fine for me.

`pod 'HyperSnapSDK', :git => 'https://github.com/hyperverge/capture-ios-sdk.git'`

Xcode - `11.6 (11E708)`
Swift - `Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)`
